### ISSUE TITLE
Watts Up Software

### ISSUE THREAD

**Issue by pkuck** [yyongpil/wattsup#1]
Hello - I'm curious if you have a zip file of the original software zip file. The company went out of business and the only place you could get the software is their website – they never provided discs with it.

Thanks,

**Comment by yyongpil** [comment]
Hi,
As far as I remember, the meter didn't come with software and that's why I wrote this script.
There used to be an API documentation on their website and this script was written using the API.
Unfortunately, their website seems down at the moment.
Thanks
